### ISSUE TITLE
某些特殊情况下，修改字体不起作用

### ISSUE THREAD

**Issue by whmzsu** [AndersonBY/pptx-ea-font#1]
我调试得到的情况是xml关于字体的顺序会影响字体的设置。
原始状态 

<a:r><a:rPr lang="zh-CN" altLang="en-US" sz="6000" dirty="0">
<a:solidFill>
<a:srgbClr val="990033"/>
</a:solidFill>
<a:latin typeface="Times New Roman" panose="02020603050405020304" pitchFamily="18" charset="0"/>
<a:cs typeface="Times New Roman" panose="02020603050405020304" pitchFamily="18" charset="0"/>
</a:rPr>
<a:t>如何解决代码冲突？</a:t>
</a:r>

修改后的状态-不起作用
<a:r>
<a:rPr lang="zh-CN" altLang="en-US" sz="6000" dirty="0">
<a:solidFill>
<a:srgbClr val="990033"/>
</a:solidFill>
<a:latin typeface="方正兰亭黑简体" panose="02020603050405020304" pitchFamily="49" charset="-122"/>
<a:cs typeface="Times New Roman" panose="02020603050405020304" pitchFamily="18" charset="0"/>
<a:ea typeface="方正兰亭黑简体" />
</a:rPr>
<a:t>如何解决代码冲突？</a:t>
</a:r>

但是如果把顺序换一下，就起作用了
<a:r>
<a:rPr lang="zh-CN" altLang="en-US" sz="6000" dirty="0">
<a:solidFill>
<a:srgbClr val="990033"/>
</a:solidFill>
<a:latin typeface="方正兰亭黑简体" panose="02020603050405020304" pitchFamily="49" charset="-122"/>
<a:ea typeface="方正兰亭黑简体" />
<a:cs typeface="Times New Roman" panose="02020603050405020304" pitchFamily="18" charset="0"/>
</a:rPr>
<a:t>如何解决代码冲突？</a:t>
</a:r>

**Comment by AndersonBY** [comment]
刚刚改成插入到首位而不是append到最后了，应该是可以解决这个问题了。

**Comment by whmzsu** [comment]
对，插入到前面可以，但是字体颜色属性丢失了，我觉的这种情况是
原始字体是
<a:cs typeface="Times New Roman" panose="02020603050405020304" pitchFamily="18" charset="0"/>
或者（这种也改不了中文字体）
<a:sym typeface="Arial" panose="020B0604020202020204" pitchFamily="34" charset="0"/>
这种控制的，没有带中文a:ea标签
看看是否有替换标签的办法，把a:cs 或者 a:sym  替换成 a:ea
问题是不知道是否还有其他各种标签，很难各种情况都考虑到

当前我判断是否是中文字符是通过 if '\u4e00' <= run.text <= '\u9fa5':  来判断的

**Comment by AndersonBY** [comment]
> 对，插入到前面可以，但是字体颜色属性丢失了，我觉的这种情况是 原始字体是 <a:cs typeface="Times New Roman" panose="02020603050405020304" pitchFamily="18" charset="0"/> 或者（这种也改不了中文字体） <a:sym typeface="Arial" panose="020B0604020202020204" pitchFamily="34" charset="0"/> 这种控制的，没有带中文a:ea标签 看看是否有替换标签的办法，把a:cs 或者 a:sym 替换成 a:ea 问题是不知道是否还有其他各种标签，很难各种情况都考虑到
> 
> 当前我判断是否是中文字符是通过 if '\u4e00' <= run.text <= '\u9fa5': 来判断的

新改了一版，应该解决了颜色问题
